# Generated by Django 4.0.1 on 2022-01-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_address', models.CharField(max_length=200)),
                ('arrival_time', models.DateTimeField(verbose_name='arrival time')),
                ('sharability', models.BooleanField(default=False)),
                ('passenger_number', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
