# Generated by Django 4.0.1 on 2022-01-28 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='status',
        ),
        migrations.AddField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ride.driver'),
        ),
        migrations.AddField(
            model_name='ride',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
