# Generated by Django 4.0.1 on 2022-01-26 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_vehicle_ride_status_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='user_id',
            new_name='user',
        ),
    ]
