# Generated by Django 4.0.1 on 2022-02-09 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('license', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_address', models.CharField(max_length=200)),
                ('arrival_datetime', models.DateTimeField(null=True)),
                ('sharability', models.BooleanField(default=False)),
                ('passenger_number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('OP', 'Open'), ('CF', 'Confirmed'), ('CP', 'Completed'), ('CC', 'Canceled')], default='OP', max_length=2)),
                ('type', models.CharField(blank=True, choices=[('SD', 'Sedan'), ('CP', 'Coupe'), ('SC', 'Sports Car'), ('SW', 'Station Wagon'), ('HB', 'Hatchback'), ('CV', 'Convertible'), ('SUV', 'SUV'), ('MNV', 'Minivan'), ('PT', 'Pickup Truck')], max_length=3)),
                ('optional', models.CharField(blank=True, max_length=200)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ride.driver')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SD', 'Sedan'), ('CP', 'Coupe'), ('SC', 'Sports Car'), ('SW', 'Station Wagon'), ('HB', 'Hatchback'), ('CV', 'Convertible'), ('SUV', 'SUV'), ('MNV', 'Minivan'), ('PT', 'Pickup Truck')], max_length=3)),
                ('plate_number', models.CharField(max_length=10)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('specialInfo', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ShareRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_number', models.PositiveSmallIntegerField()),
                ('ride', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ride.ride')),
                ('sharer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ride.vehicle'),
        ),
    ]
